package com.mygdx.game.enums;

public enum DynamicElementPartType {
	
	TRACK_LEFT_PLAYER,
	TRACK_RIGHT_PLAYER,
	EXHAUST_LEFT_PLAYER,
	EXHAUST_RIGHT_PLAYER,
	PRINT_TRACK_LEFT_PLAYER,
	PRINT_TRACK_RIGHT_PLAYER,
	HULL_PLAYER,
	GUN_PLAYER,
	
	LEFT_WING_ENEMY_1,
	RIGHT_WING_ENEMY_1,
	BODY_ENEMY_1,
	
	TRACK_LEFT_ENEMY_2,
	TRACK_RIGHT_ENEMY_2,
	EXHAUST_LEFT_ENEMY_2,
	EXHAUST_RIGHT_ENEMY_2,
	HULL_ENEMY_2,
	GUN_ENEMY_2,
	
	BADGE,
	BONUS;
}
